In [14]:
#This notebook Explains use of numpy.resize and numpy.reshape functions and explains there usage
import numpy as np

In [20]:
#Let's take an example array as below of shape(3,4)
a=np.array([[0,1,5,6],[2,3,4,3],[5,3,4,6]])
a

array([[0, 1, 5, 6],
       [2, 3, 4, 3],
       [5, 3, 4, 6]])

In [39]:
#We can increase or decrease the size of this array using np.resize function.
#This function is important because it may be required in processing datasets with arrays of diiferent lengths.
#resize functions requires 2 arguments apart from optional one's.
#First argument is the array to be resized and Second argument is the size of the new array required as output. 
a=np.resize(a,(10,10))
print("New Array of shape(10,10)\n")
print(a)
#The output repeats the entries of the array to populate the new array
print("\nNew Array of shape(14,13)\n")
print(np.resize(a,(14,13)))

New Array of shape(10,10)

[[0 1 5 6 2 3 4 3 5 3]
 [4 6 0 1 5 6 2 3 4 3]
 [5 3 4 6 0 1 5 6 2 3]
 [4 3 5 3 4 6 0 1 5 6]
 [2 3 4 3 5 3 4 6 0 1]
 [5 6 2 3 4 3 5 3 4 6]
 [0 1 5 6 2 3 4 3 5 3]
 [4 6 0 1 5 6 2 3 4 3]
 [5 3 4 6 0 1 5 6 2 3]
 [4 3 5 3 4 6 0 1 5 6]]

New Array of shape(14,13)

[[0 1 5 6 2 3 4 3 5 3 4 6 0]
 [1 5 6 2 3 4 3 5 3 4 6 0 1]
 [5 6 2 3 4 3 5 3 4 6 0 1 5]
 [6 2 3 4 3 5 3 4 6 0 1 5 6]
 [2 3 4 3 5 3 4 6 0 1 5 6 2]
 [3 4 3 5 3 4 6 0 1 5 6 2 3]
 [4 3 5 3 4 6 0 1 5 6 2 3 4]
 [3 5 3 4 6 0 1 5 6 0 1 5 6]
 [2 3 4 3 5 3 4 6 0 1 5 6 2]
 [3 4 3 5 3 4 6 0 1 5 6 2 3]
 [4 3 5 3 4 6 0 1 5 6 2 3 4]
 [3 5 3 4 6 0 1 5 6 2 3 4 3]
 [5 3 4 6 0 1 5 6 2 3 4 3 5]
 [3 4 6 0 1 5 6 2 3 4 3 5 3]]


In [41]:
#The reshape function can be used to change the shape of the array.
#It is useful in those situations where we need to reduce the dimension of an array for processing
print(a.shape)
a=np.reshape(a,(2,50))
print("\nReshaped Array\n")
print(a)
print(a.shape)
a=np.reshape(a,(4,25))
print("\nReshaped Array\n")
print(a)
print(a.shape)

(2, 50)

Reshaped Array

[[0 1 5 6 2 3 4 3 5 3 4 6 0 1 5 6 2 3 4 3 5 3 4 6 0 1 5 6 2 3 4 3 5 3 4 6
  0 1 5 6 2 3 4 3 5 3 4 6 0 1]
 [5 6 2 3 4 3 5 3 4 6 0 1 5 6 2 3 4 3 5 3 4 6 0 1 5 6 2 3 4 3 5 3 4 6 0 1
  5 6 2 3 4 3 5 3 4 6 0 1 5 6]]
(2, 50)

Reshaped Array

[[0 1 5 6 2 3 4 3 5 3 4 6 0 1 5 6 2 3 4 3 5 3 4 6 0]
 [1 5 6 2 3 4 3 5 3 4 6 0 1 5 6 2 3 4 3 5 3 4 6 0 1]
 [5 6 2 3 4 3 5 3 4 6 0 1 5 6 2 3 4 3 5 3 4 6 0 1 5]
 [6 2 3 4 3 5 3 4 6 0 1 5 6 2 3 4 3 5 3 4 6 0 1 5 6]]
(4, 25)
